### ISSUE TITLE
several bugs

### ISSUE THREAD

**Issue by Jackiexiao** [yangdongchao/UniAudio#15]
running TTS egs

1. text_tokenizer.py

https://github.com/yangdongchao/UniAudio/blob/b4da009653486828b4d71a6efe1772b1403ce324/UniAudio/tools/tokenizer/phone/text_tokenizer.py#L12

no TextTokenizer

```
class Text2PhoneTokenizer(AbsTokenizer):
    def __init__(self, langdir='UniAudio/checkpoints/lang_nosp'):
        super(TextTokenizer, self).__init__()
```

2. offline_tokenization.py

```
  5 Traceback (most recent call last):
  6   File "data_scripts/offline_tokenization.py", line 161, in <module>
  7     main(sys.argv[1:])
  8   File "data_scripts/offline_tokenization.py", line 70, in main
  9     tokenizer = PhoneTokenizer(duplicate=True)
 10 TypeError: __init__() got an unexpected keyword argument 'duplicate'
```

**Comment by Cris140** [comment]
I'm having the same problem, were you able to make it work?

**Comment by Jackiexiao** [comment]
> I'm having the same problem, were you able to make it work?

1. easy to fix
2. just remove duplicate=True (I guess)

**Comment by Cris140** [comment]
Yes, that worked, but now it's asking for a config.yaml, how can I generate or get one?

**Comment by pawanhv** [comment]
hi,
Yes where can i find the config.yaml?
